import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";

const RENDER_DELAY = 1000;

type DeferredProps = {
  message: string;
};
const Deferred: NextPage<DeferredProps> = (props) => {
  const { message } = props;
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Deferred: {router.isFallback ? "Rendering..." : message}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {router.isFallback ? (
          <>
            <p className={styles.description}>Rendering&hellip;</p>
          </>
        ) : (
          <>
            <h1 className={styles.title}>{message}</h1>
            <p className={styles.description}>
              This page is rendered on first access. The static content is
              reused for subsequent calls.
            </p>
            <Link href="/">
              <a>Home</a>
            </Link>
          </>
        )}
      </main>
    </div>
  );
};
export default Deferred;

export const getStaticProps: GetStaticProps<DeferredProps> = async (
  context
) => {
  await new Promise((res) => setTimeout(res, RENDER_DELAY));

  const message = context.params?.message;
  if (!message)
    return {
      notFound: true,
    };
  return {
    props: {
      message: Array.isArray(message) ? message.join(" ") : message,
    },
  };
};

export const getStaticPaths: GetStaticPaths = (context) => {
  return {
    fallback: "blocking",
    paths: [],
  };
};
