import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/deferred/hello%20world">
          <a>Generate a page</a>
        </Link>
        <Link href="/static">
          <a>Static page</a>
        </Link>
        <Link href="/api/test">
          <a>API route</a>
        </Link>
        <Link href="/api/preview">
          <a>Enable preview</a>
        </Link>
        <Link href="/api/exit-preview">
          <a>Exit preview</a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
