import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Static page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Static page</h1>
        <p className={styles.description}>This page is statically rendered.</p>
        <Link href="/">
          <a>Home</a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
